# Generated by Django 6.0.6 on 2026-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_task_completed_task_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
