# Generated by Django 6.0.6 on 2026-06-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_task_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='task',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
